### PR TITLE
Shapes!

### PR DESCRIPTION
**Pull request by alexapostolu**
## Shapes!
Shapes are now working!
Main file I worked on: `EditorController.java`

**New Features**
* select circle or square to draw
* chose fill/stroke colour, stroke width
* drag and draw circle and square
* clear canvas to erase shapes
* you can undo clearing a canvas
* fix bugs with text drawing and text size buttons

**Improvements**
* refactored `EditorController.java` by removing redundant code and organizing the structure in a more readable way
* basic refactoring of the Visual Elements to work better with `EditorController.java`

Screenshot (34)

**Next Steps**
* add error checking on text fields for text size and stroke width
* organize file structure
* move all static initializers in `.java` to `.fxml` where possible (?)

### CODE REVIEW

**Comment by latxh** [comment]
Getting a ton of errors on this build:

-Cant brush draw at all
-When I try to use shapes I get console errors:
image

**Comment by AlexMirabella** [comment]
I can't find your branch on IntelliJ, so I'm unsure how to run your code to check what Brian is saying. I tried running it in a codespace and something did seem to fail, but I'm not confident with that thing anyway. None of your changes seem like they could do something like that to me though.
Maybe, if Brian is amenable, we could get in a quick call today to examine the issue?

**Review by AlexMirabella — DISMISSED** [review]
Turns out the issue was that you have to put in an integer for the stroke size. Nothing is broken, but we need to catch that. I say this should be approved.

**Review by latxh — CHANGES_REQUESTED** [review]
Seems like alot of bugs in regards to:
-Free draw does not work
-Clear canvas does not work (deleted canvas reappears after next drawing)
-Text is only able to draw once and then sometimes disappears
-No default tool selected
-No default value for outline number

Pulling in main should be a good first step and may fix some of this but I quickly did so and seems like its quite buggy still

**Review by latxh — DISMISSED** [review]
Looks good to me now! Bugs gone, minus square functionality acting a bit weird

**Review by latxh — APPROVED** [review]

**Pull request merged**
