### PR TITLE
Editor UI improvements

### PR DESCRIPTION
**Pull request by latxh**
-Custom styling for dropdowns, chcekboxes, color picker
-New styling for Tool Selection

image

image

image

image

### CODE REVIEW

**Review by SquaredPiano — DISMISSED** [review]
The new UI looks really intuitive and well thought out! These are really impressive changes, and the UI seems a lot more user-friendly.

**Review by SquaredPiano — DISMISSED** [review]
The new UI looks really intuitive and well thought out! These are really impressive changes, and the UI seems a lot more user-friendly.

**Comment by alexapostolu** [comment]
the new features look super clean! not sure about vishnu's background colour changes and their implications on larger screens!

**Comment by latxh** [comment]
Reverted Vishnu's background colour changes as they do not follow the UX

**Review by AlexMirabella — APPROVED** [review]
LGTM. Love the new icons

**Review by alexapostolu — APPROVED** [review]
lgtm

**Pull request merged**
