### PR TITLE
Alexm freedraw and create project

### PR DESCRIPTION
**Pull request by AlexMirabella**
Added a FreeDrawLine class that will store the information of a free drawn line, and I added some code to FXMLController and an fxml file so that there's a new add name page before you go to the editor when you create a new project.

### CODE REVIEW

**Review by alexapostolu — APPROVED** [review]
LGTM!

**Review by AmaruIzarra — COMMENTED** [review]
Looks good! I will work off the condition you added for sign in to make sure the user is in our DataModel.

**Review by je3songli — APPROVED** [review]
Looks good!

**Review by SquaredPiano — APPROVED** [review]
Great implementation of the free draw class and amazing stuff with the project naming UI.

**Pull request merged**
