### PR TITLE
Test folder is now recognized by IDEA, and Gradle modules graphics an…

### LINKED ISSUE #9: Test reconfigured

### PR DESCRIPTION
**Pull request by AlexMirabella**
…d base are added. Rebuild necessary

### CODE REVIEW

**Comment by AlexMirabella** [comment]
I added folder to test so that now it's automatically registered by IDEA, and added some modules to build.gradle

**Review by alexapostolu — DISMISSED** [review]
LGTM!

**Review by je3songli — DISMISSED** [review]
I think this looks good!

**Review by AmaruIzarra — APPROVED** [review]

**Review by SquaredPiano — DISMISSED** [review]
Nice job with the changes.

**Comment by je3songli** [comment]
Looks very good

**Review by AmaruIzarra — APPROVED** [review]

**Review by alexapostolu — APPROVED** [review]
LGTM!

**Pull request merged**
