### PR TITLE
Editor UI + General UI Cleanup

### LINKED ISSUE #12: Editor (View)
Image

### LINKED ISSUE #32: Navigate between Editor and Your Projects Views
Image

Image

### PR DESCRIPTION
**Pull request by latxh**
Changes:
-Added editor UI page and routing
-Added all icons for the editor UI
-Made the create project button route to the editor page
-Made Signin/Signup/Projects pages slightly smaller (since they can not currently be resized)

image

### CODE REVIEW

**Review by je3songli — APPROVED** [review]
This looks really good! I like the layout and organization of all the features, as well as how when we hover over the feature, we can see its name/function. I wonder if there's a way to make the icons more clear, and have the canvas contrast more from the background. However, those are really minor details.

**Review by AmaruIzarra — APPROVED** [review]

**Review by SquaredPiano — APPROVED** [review]
The Editor UI looks really well thought out and the respective icons are a great addition! The MarkUp seems really well done and the organization of the UI looks really clean! Awesome stuff

**Review by AlexMirabella — COMMENTED** [review]
The editor looks really pretty! I think the "create project" button needs to redirect to a createProject function before switching to editor. Just to make sure, that would involve changing what code in the fxml?

**Review by alexapostolu — APPROVED** [review]
Looks good! Icons work well and everything is organized

**Pull request merged**
