### PR TITLE
Added user features

### PR DESCRIPTION
**Pull request by AmaruIzarra**
Adding user classes: User class that creates a user object with given attributes, User Login and User Register use cases, and a data file gateway that allows access to JSON file that will store all the different users and projects that are saved.

### CODE REVIEW

**Review by SquaredPiano — APPROVED** [review]
Great implementation of the sign-in and sign-up features! Have tested the features and the application seems to run well. Will conduct further testing. Great stuff tho!

**Review by alexapostolu — APPROVED** [review]
LGTM! code is readable and makes sense!

**Review by AlexMirabella — COMMENTED** [review]
Great job! I'm impressed you managed to figure out all the json file stuff. Your code is really well organized from a code layers perspective as well.

**Comment by je3songli** [comment]
Looks good! I like how everything is organized, and it'll serve as a good base for connecting to the rest of the program. In the future we can add more comments and javadoc.

**Pull request merged**
