### PR TITLE
Added Canvas Text features

### LINKED ISSUE #23: Draw Text
Image

### PR DESCRIPTION
**Pull request by je3songli**
Added features for: writing text to a specific coordinates, changing font family, changing font colour, changing font size
Created AardText class to represent the text class and its attributes

image

### CODE REVIEW

**Review by SquaredPiano — APPROVED** [review]
I like the features, and would love to see it integrated into a more modulated and encapsulated architected program! I will merge the features onto my own branch. Overall, great stuff!

**Comment by alexapostolu** [comment]
I have some issues with this (joke). I think the code would be shorter if each text option was stored in an array and we used polymorphism to call the function as right now there's a lot of duplicate code. But dw we'll fix this later

**Review by AmaruIzarra — APPROVED** [review]
Looks good! Maybe try rebasing the view to look more clean. Also possible room for improvement is to add more possible font choices.

**Comment by AlexMirabella** [comment]
This looks really good! I'm glad you managed to create the feature while making it compatible with the VisualElement interface!

**Pull request merged**
