### PR TITLE
Refactoring projects work flow

### PR DESCRIPTION
**Pull request by AmaruIzarra**
Refactored MainAppRouter, UserDSGateway, and Projects to in order to more closely follow clean architecture.

### CODE REVIEW

**Review by SquaredPiano — DISMISSED** [review]
LGTM!

**Comment by alexapostolu** [comment]
LGTM!

**Review by AlexMirabella — COMMENTED** [review]
Awesome changes! MainAppRouter looks so much cleaner now! No wonder its called clean architecture...

**Review by SquaredPiano — DISMISSED** [review]
Reviewed, the changes look really clean!

**Review by alexapostolu — APPROVED** [review]
LGTM!

**Review by latxh — APPROVED** [review]
lgtm

**Review by SquaredPiano — APPROVED** [review]
LGTM!

**Pull request merged**
